# Generated by Django 5.2.4 on 2025-08-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughtsapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
